spring:
  redis:
    host: 127.0.0.1
    port: 5017
    password: hejiyao
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
